name: issue-opener
on:
  issues:
    types: [opened]
jobs:
  open-transformer-issues:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Comment on issue #${{ github.event.label }}"
      - uses: actions/checkout@v2
      - name: Open a designer transformer issue 
        if: contains( toJson(github), 'transformer' )
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/designer-transformer-template.md
      - name: Open a jenkinsfile transformer issue
        if: contains( toJson(github), 'transformer' )
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/jenkinsfile-transformer-template.md
      - name: Close original transformer issue
        if: contains( toJson(github), 'transformer' )
        uses: peter-evans/close-issue@v1
        with:
          comment: |
            Auto closing this issue.

  open-only-designer-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Open a designer transformer issue 
        if: contains( toJson(github), 'jenkinsfile-transformer' )
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/designer-transformer-template.md
 
  open-only-jenkinsfile-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Open a jenkinsfile transformer issue 
        if: contains( toJson(github), 'designer-transformer' )
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/jenkinsfile-transformer-template.md
