name: issue-opener
on:
  issues:
    types: [opened]
jobs:
  open-transformer-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  open-designer-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Open a designer transformer issue 
        if: contains( github.event.issue.labels.*.name, 'jenkinsfile-transformer')
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/invisible_issue_templates/DESIGNER.md
      - name: test 
        run: echo github.event.issue.number == steps.create-issue.outputs.number
      - name: Assign this issue to Valet project
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: github.event.action == 'opened' && (github.event.issue.number == steps.create-issue.outputs.number)
        with:
          project: 'https://github.com/sophiederosa/workflow-testing/projects/1'
 
  open-jenkinsfile-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Open a jenkinsfile transformer issue 
        if: contains( github.event.issue.labels.*.name, 'designer-transformer')
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/invisible_issue_templates/JENKINSFILE.md
      - name: Assign this issue to Valet project
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: github.event.action == 'opened' && (github.event.issue.number == steps.create-issue.outputs.number)
        with:
          project: 'https://github.com/sophiederosa/workflow-testing/projects/1'
