name: issue-opener
on:
  issues:
    types: [opened]
jobs:
  open-new-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Open a designer transformer issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/designer-transformer-template.md
        if: ${{ github.event.label.name }} == 'transformer' || ${{ github.event.label.name }} == 'jenkinsfile-transformer'
      - name: Open a jenkinsfile transformer issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/jenkinsfile-transformer-template.md
        if:  ${{ github.event.label.name }} == 'transformer' || ${{ github.event.label.name }} == 'designer-transformer'
      - name: Close original transformer issue
        uses: peter-evans/close-issue@v1
        if:  ${{ github.event.label.name }} == 'transformer'
        with:
          comment: |
            Auto closing this issue.
