on: 
  workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: install homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: install act
      run: brew install -s act
    - name: run act
      run: act -n -P ubuntu-latest=catthehacker/ubuntu:act-latest
