on: 
  workflow_dispatch

jobs:
  validate_workflows:
    runs-on: ubuntu-latest
    name: Validate new workflow files
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: install act
      run: brew install -s act
    - name: run act
      run: act
